### ISSUE TITLE
wrong user returned by active_directory.find_user

### ISSUE THREAD

**Issue by abma** [tjguk/active_directory#2]
active_directory.find_user() returns the wrong user when two users exist:

ie.:

user2
user

active_directory.find_user("user")

returns user2 in some cases

**Comment by tjguk** [comment]
The module-level .find_user is a quick&dirty function which uses AD's ANR to do a fuzzy match. (Ambiguous Name Resolution). If you need to match a name exactly, ie for more than a casual lookup, use the .search function, eg:

goldent = active_directory.search(objectClass="User", samAccountName="goldent").next()

(NB the search function returns a generator)

**Comment by abma** [comment]
would be nice if this could be added to the docstring of find_user:

https://github.com/tjguk/active_directory/blob/master/active_directory.py#L1013 :)

**Comment by abma** [comment]
+ thanks a lot for the (working) example!
